name: ${project.name}
main: net.daboross.bukkitdev.arrows.ArrowsPlugin
version: ${project.version}
author: Dabo Ross
description: ${project.description}
url: https://github.com/daboross/Arrows
commands:
  ua: